# Jekyll configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-us'

name: 'CI Wise Inc.'
description: "Your dreams. Our design"

# Author's info
author: 'David L. Whitehurst'
# edit 'categories' in the front matter of every post to match this username
nickname: dlwhitehurst
# was casper
bio: 'Chief Executive Officer, Principal Consultant, and Agile Software Developer for the CI Wise Corporation. An enterprise open source expert and information systems specialist for over 3 decades.'
location: 'Raleigh, North Carolina, USA'
url: 'http://ciwise.com'
image: 'assets/images/me.png'

short_url: 'ciwise.com'
google_analytics: UA-72650913-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: dlwhitehurst 
repo: ciwise.github.io 
branch: master
relative_source: ../ciwise.github.custom 
#destination: ../ciwise.github.custom/_site 
destination: ../ciwise.github.io 
production_url:  https://biomadeira.github.io/jasper/
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
